syntax = "proto2";
message ShannonLteUECap {
  //Version
  required uint32 version = 1;

  // Supported LTE carrier-aggregation combinations.
  repeated Combo combos = 2;

  //Bitmask
  required uint32 bitmask = 3;
}

message Combo {
  // Band components
  repeated Component components = 1;
 // BCS 0 uses bit 31, BCS 1 uses bit 30 etc
  optional uint32 bcs = 2;
  // conf_id from 0 to 63 uint64
  required uint64 conf_id0to63 = 3;
  // conf_id 64 to 96 uint32
  required uint32 conf_id64to96 = 4;
}

message Component {
  // LTE band number.
  required int32 band = 1;
  // A = 32768
  // B = 16384
  // C = 8192
  // D = 4096
  // E = 2048
  // F = 1024
  // If Odd num  = 4L e.g 32769, 8193, 4097 etc
  required int32 bwClassMimoDl = 2;
  required int32 bwClassMimoUl = 3;
}
